version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Add any pre-build steps here (e.g., installing dependencies)

      - run:
          name: Build Docker image
          command: docker build -t testingit123 .

      - run:
          name: Push Docker image to registry
          command: docker push testingmyfile123/testingit123

  deploy:
    machine:
      enabled: true

    steps:
      - checkout

      - run:
          name: Install Docker
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sudo sh get-docker.sh

      - run:
          name: Pull Docker image from registry
          command: docker pull your-testingmyfile123/testingit123

      # Add any additional deployment steps here

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main

      - deploy:
          requires:
            - build
